/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DotDotDotDotDotDotReactSrcRoutesIndexRouteImport } from './../../react/src/routes/index'
import { Route as DotDotDotDotDotDotReactSrcRoutesToolsRouteImport } from './../../react/src/routes/tools'
import { Route as DotDotDotDotDotDotReactSrcRoutesToolkitsRouteImport } from './../../react/src/routes/toolkits'
import { Route as DotDotDotDotDotDotReactSrcRoutesSkillsRouteImport } from './../../react/src/routes/skills'
import { Route as SecretsRouteImport } from './routes/app/secrets'
import { Route as DotDotDotDotDotDotReactSrcRoutesPoliciesRouteImport } from './../../react/src/routes/policies'
import { Route as DotDotDotDotDotDotReactSrcRoutesArtifactsRouteImport } from './../../react/src/routes/artifacts'
import { Route as DotDotDotDotDotDotReactSrcRoutesToolkitsDottoolkitSlugRouteImport } from './../../react/src/routes/toolkits.$toolkitSlug'
import { Route as DotDotDotDotDotDotReactSrcRoutesSkillsDotnewRouteImport } from './../../react/src/routes/skills.new'
import { Route as DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdRouteImport } from './../../react/src/routes/skills.$skillId'
import { Route as DotDotDotDotDotDotReactSrcRoutesResumeDotexecutionIdRouteImport } from './../../react/src/routes/resume.$executionId'
import { Route as DotDotDotDotDotDotReactSrcRoutesIntegrationsDotbrowseRouteImport } from './../../react/src/routes/integrations.browse'
import { Route as DotDotDotDotDotDotReactSrcRoutesIntegrationsDotnamespaceRouteImport } from './../../react/src/routes/integrations.$namespace'
import { Route as DotDotDotDotDotDotReactSrcRoutesConnectDotintegrationSlugRouteImport } from './../../react/src/routes/connect.$integrationSlug'
import { Route as DotDotDotDotDotDotReactSrcRoutesArtifactsDotartifactIdRouteImport } from './../../react/src/routes/artifacts.$artifactId'
import { Route as DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdDoteditRouteImport } from './../../react/src/routes/skills.$skillId.edit'
import { Route as DotDotDotDotDotDotReactSrcRoutesPluginsDotpluginIdDotsplatRouteImport } from './../../react/src/routes/plugins.$pluginId.$'
import { Route as DotDotDotDotDotDotReactSrcRoutesIntegrationsDotaddDotpluginKeyRouteImport } from './../../react/src/routes/integrations.add.$pluginKey'
import { Route as DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdDotupdatesDotcandidateIdRouteImport } from './../../react/src/routes/skills.$skillId.updates.$candidateId'

const DotDotDotDotDotDotReactSrcRoutesIndexRoute =
  DotDotDotDotDotDotReactSrcRoutesIndexRouteImport.update({
    id: '/{-$orgSlug}/',
    path: '/{-$orgSlug}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotReactSrcRoutesToolsRoute =
  DotDotDotDotDotDotReactSrcRoutesToolsRouteImport.update({
    id: '/{-$orgSlug}/tools',
    path: '/{-$orgSlug}/tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotReactSrcRoutesToolkitsRoute =
  DotDotDotDotDotDotReactSrcRoutesToolkitsRouteImport.update({
    id: '/{-$orgSlug}/toolkits',
    path: '/{-$orgSlug}/toolkits',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotReactSrcRoutesSkillsRoute =
  DotDotDotDotDotDotReactSrcRoutesSkillsRouteImport.update({
    id: '/{-$orgSlug}/skills',
    path: '/{-$orgSlug}/skills',
    getParentRoute: () => rootRouteImport,
  } as any)
const SecretsRoute = SecretsRouteImport.update({
  id: '/{-$orgSlug}/secrets',
  path: '/{-$orgSlug}/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const DotDotDotDotDotDotReactSrcRoutesPoliciesRoute =
  DotDotDotDotDotDotReactSrcRoutesPoliciesRouteImport.update({
    id: '/{-$orgSlug}/policies',
    path: '/{-$orgSlug}/policies',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotReactSrcRoutesArtifactsRoute =
  DotDotDotDotDotDotReactSrcRoutesArtifactsRouteImport.update({
    id: '/{-$orgSlug}/artifacts',
    path: '/{-$orgSlug}/artifacts',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotReactSrcRoutesToolkitsDottoolkitSlugRoute =
  DotDotDotDotDotDotReactSrcRoutesToolkitsDottoolkitSlugRouteImport.update({
    id: '/$toolkitSlug',
    path: '/$toolkitSlug',
    getParentRoute: () => DotDotDotDotDotDotReactSrcRoutesToolkitsRoute,
  } as any)
const DotDotDotDotDotDotReactSrcRoutesSkillsDotnewRoute =
  DotDotDotDotDotDotReactSrcRoutesSkillsDotnewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => DotDotDotDotDotDotReactSrcRoutesSkillsRoute,
  } as any)
const DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdRoute =
  DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdRouteImport.update({
    id: '/$skillId',
    path: '/$skillId',
    getParentRoute: () => DotDotDotDotDotDotReactSrcRoutesSkillsRoute,
  } as any)
const DotDotDotDotDotDotReactSrcRoutesResumeDotexecutionIdRoute =
  DotDotDotDotDotDotReactSrcRoutesResumeDotexecutionIdRouteImport.update({
    id: '/{-$orgSlug}/resume/$executionId',
    path: '/{-$orgSlug}/resume/$executionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotReactSrcRoutesIntegrationsDotbrowseRoute =
  DotDotDotDotDotDotReactSrcRoutesIntegrationsDotbrowseRouteImport.update({
    id: '/{-$orgSlug}/integrations/browse',
    path: '/{-$orgSlug}/integrations/browse',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotReactSrcRoutesIntegrationsDotnamespaceRoute =
  DotDotDotDotDotDotReactSrcRoutesIntegrationsDotnamespaceRouteImport.update({
    id: '/{-$orgSlug}/integrations/$namespace',
    path: '/{-$orgSlug}/integrations/$namespace',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotReactSrcRoutesConnectDotintegrationSlugRoute =
  DotDotDotDotDotDotReactSrcRoutesConnectDotintegrationSlugRouteImport.update({
    id: '/{-$orgSlug}/connect/$integrationSlug',
    path: '/{-$orgSlug}/connect/$integrationSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotReactSrcRoutesArtifactsDotartifactIdRoute =
  DotDotDotDotDotDotReactSrcRoutesArtifactsDotartifactIdRouteImport.update({
    id: '/$artifactId',
    path: '/$artifactId',
    getParentRoute: () => DotDotDotDotDotDotReactSrcRoutesArtifactsRoute,
  } as any)
const DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdDoteditRoute =
  DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdDoteditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdRoute,
  } as any)
const DotDotDotDotDotDotReactSrcRoutesPluginsDotpluginIdDotsplatRoute =
  DotDotDotDotDotDotReactSrcRoutesPluginsDotpluginIdDotsplatRouteImport.update({
    id: '/{-$orgSlug}/plugins/$pluginId/$',
    path: '/{-$orgSlug}/plugins/$pluginId/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute =
  DotDotDotDotDotDotReactSrcRoutesIntegrationsDotaddDotpluginKeyRouteImport.update(
    {
      id: '/{-$orgSlug}/integrations/add/$pluginKey',
      path: '/{-$orgSlug}/integrations/add/$pluginKey',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdDotupdatesDotcandidateIdRoute =
  DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdDotupdatesDotcandidateIdRouteImport.update(
    {
      id: '/updates/$candidateId',
      path: '/updates/$candidateId',
      getParentRoute: () =>
        DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/{-$orgSlug}/artifacts': typeof DotDotDotDotDotDotReactSrcRoutesArtifactsRouteWithChildren
  '/{-$orgSlug}/policies': typeof DotDotDotDotDotDotReactSrcRoutesPoliciesRoute
  '/{-$orgSlug}/secrets': typeof SecretsRoute
  '/{-$orgSlug}/skills': typeof DotDotDotDotDotDotReactSrcRoutesSkillsRouteWithChildren
  '/{-$orgSlug}/toolkits': typeof DotDotDotDotDotDotReactSrcRoutesToolkitsRouteWithChildren
  '/{-$orgSlug}/tools': typeof DotDotDotDotDotDotReactSrcRoutesToolsRoute
  '/{-$orgSlug}/': typeof DotDotDotDotDotDotReactSrcRoutesIndexRoute
  '/{-$orgSlug}/artifacts/$artifactId': typeof DotDotDotDotDotDotReactSrcRoutesArtifactsDotartifactIdRoute
  '/{-$orgSlug}/connect/$integrationSlug': typeof DotDotDotDotDotDotReactSrcRoutesConnectDotintegrationSlugRoute
  '/{-$orgSlug}/integrations/$namespace': typeof DotDotDotDotDotDotReactSrcRoutesIntegrationsDotnamespaceRoute
  '/{-$orgSlug}/integrations/browse': typeof DotDotDotDotDotDotReactSrcRoutesIntegrationsDotbrowseRoute
  '/{-$orgSlug}/resume/$executionId': typeof DotDotDotDotDotDotReactSrcRoutesResumeDotexecutionIdRoute
  '/{-$orgSlug}/skills/$skillId': typeof DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdRouteWithChildren
  '/{-$orgSlug}/skills/new': typeof DotDotDotDotDotDotReactSrcRoutesSkillsDotnewRoute
  '/{-$orgSlug}/toolkits/$toolkitSlug': typeof DotDotDotDotDotDotReactSrcRoutesToolkitsDottoolkitSlugRoute
  '/{-$orgSlug}/integrations/add/$pluginKey': typeof DotDotDotDotDotDotReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute
  '/{-$orgSlug}/plugins/$pluginId/$': typeof DotDotDotDotDotDotReactSrcRoutesPluginsDotpluginIdDotsplatRoute
  '/{-$orgSlug}/skills/$skillId/edit': typeof DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdDoteditRoute
  '/{-$orgSlug}/skills/$skillId/updates/$candidateId': typeof DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdDotupdatesDotcandidateIdRoute
}
export interface FileRoutesByTo {
  '/{-$orgSlug}/artifacts': typeof DotDotDotDotDotDotReactSrcRoutesArtifactsRouteWithChildren
  '/{-$orgSlug}/policies': typeof DotDotDotDotDotDotReactSrcRoutesPoliciesRoute
  '/{-$orgSlug}/secrets': typeof SecretsRoute
  '/{-$orgSlug}/skills': typeof DotDotDotDotDotDotReactSrcRoutesSkillsRouteWithChildren
  '/{-$orgSlug}/toolkits': typeof DotDotDotDotDotDotReactSrcRoutesToolkitsRouteWithChildren
  '/{-$orgSlug}/tools': typeof DotDotDotDotDotDotReactSrcRoutesToolsRoute
  '/{-$orgSlug}': typeof DotDotDotDotDotDotReactSrcRoutesIndexRoute
  '/{-$orgSlug}/artifacts/$artifactId': typeof DotDotDotDotDotDotReactSrcRoutesArtifactsDotartifactIdRoute
  '/{-$orgSlug}/connect/$integrationSlug': typeof DotDotDotDotDotDotReactSrcRoutesConnectDotintegrationSlugRoute
  '/{-$orgSlug}/integrations/$namespace': typeof DotDotDotDotDotDotReactSrcRoutesIntegrationsDotnamespaceRoute
  '/{-$orgSlug}/integrations/browse': typeof DotDotDotDotDotDotReactSrcRoutesIntegrationsDotbrowseRoute
  '/{-$orgSlug}/resume/$executionId': typeof DotDotDotDotDotDotReactSrcRoutesResumeDotexecutionIdRoute
  '/{-$orgSlug}/skills/$skillId': typeof DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdRouteWithChildren
  '/{-$orgSlug}/skills/new': typeof DotDotDotDotDotDotReactSrcRoutesSkillsDotnewRoute
  '/{-$orgSlug}/toolkits/$toolkitSlug': typeof DotDotDotDotDotDotReactSrcRoutesToolkitsDottoolkitSlugRoute
  '/{-$orgSlug}/integrations/add/$pluginKey': typeof DotDotDotDotDotDotReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute
  '/{-$orgSlug}/plugins/$pluginId/$': typeof DotDotDotDotDotDotReactSrcRoutesPluginsDotpluginIdDotsplatRoute
  '/{-$orgSlug}/skills/$skillId/edit': typeof DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdDoteditRoute
  '/{-$orgSlug}/skills/$skillId/updates/$candidateId': typeof DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdDotupdatesDotcandidateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$orgSlug}/artifacts': typeof DotDotDotDotDotDotReactSrcRoutesArtifactsRouteWithChildren
  '/{-$orgSlug}/policies': typeof DotDotDotDotDotDotReactSrcRoutesPoliciesRoute
  '/{-$orgSlug}/secrets': typeof SecretsRoute
  '/{-$orgSlug}/skills': typeof DotDotDotDotDotDotReactSrcRoutesSkillsRouteWithChildren
  '/{-$orgSlug}/toolkits': typeof DotDotDotDotDotDotReactSrcRoutesToolkitsRouteWithChildren
  '/{-$orgSlug}/tools': typeof DotDotDotDotDotDotReactSrcRoutesToolsRoute
  '/{-$orgSlug}/': typeof DotDotDotDotDotDotReactSrcRoutesIndexRoute
  '/{-$orgSlug}/artifacts/$artifactId': typeof DotDotDotDotDotDotReactSrcRoutesArtifactsDotartifactIdRoute
  '/{-$orgSlug}/connect/$integrationSlug': typeof DotDotDotDotDotDotReactSrcRoutesConnectDotintegrationSlugRoute
  '/{-$orgSlug}/integrations/$namespace': typeof DotDotDotDotDotDotReactSrcRoutesIntegrationsDotnamespaceRoute
  '/{-$orgSlug}/integrations/browse': typeof DotDotDotDotDotDotReactSrcRoutesIntegrationsDotbrowseRoute
  '/{-$orgSlug}/resume/$executionId': typeof DotDotDotDotDotDotReactSrcRoutesResumeDotexecutionIdRoute
  '/{-$orgSlug}/skills/$skillId': typeof DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdRouteWithChildren
  '/{-$orgSlug}/skills/new': typeof DotDotDotDotDotDotReactSrcRoutesSkillsDotnewRoute
  '/{-$orgSlug}/toolkits/$toolkitSlug': typeof DotDotDotDotDotDotReactSrcRoutesToolkitsDottoolkitSlugRoute
  '/{-$orgSlug}/integrations/add/$pluginKey': typeof DotDotDotDotDotDotReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute
  '/{-$orgSlug}/plugins/$pluginId/$': typeof DotDotDotDotDotDotReactSrcRoutesPluginsDotpluginIdDotsplatRoute
  '/{-$orgSlug}/skills/$skillId/edit': typeof DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdDoteditRoute
  '/{-$orgSlug}/skills/$skillId/updates/$candidateId': typeof DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdDotupdatesDotcandidateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$orgSlug}/artifacts'
    | '/{-$orgSlug}/policies'
    | '/{-$orgSlug}/secrets'
    | '/{-$orgSlug}/skills'
    | '/{-$orgSlug}/toolkits'
    | '/{-$orgSlug}/tools'
    | '/{-$orgSlug}/'
    | '/{-$orgSlug}/artifacts/$artifactId'
    | '/{-$orgSlug}/connect/$integrationSlug'
    | '/{-$orgSlug}/integrations/$namespace'
    | '/{-$orgSlug}/integrations/browse'
    | '/{-$orgSlug}/resume/$executionId'
    | '/{-$orgSlug}/skills/$skillId'
    | '/{-$orgSlug}/skills/new'
    | '/{-$orgSlug}/toolkits/$toolkitSlug'
    | '/{-$orgSlug}/integrations/add/$pluginKey'
    | '/{-$orgSlug}/plugins/$pluginId/$'
    | '/{-$orgSlug}/skills/$skillId/edit'
    | '/{-$orgSlug}/skills/$skillId/updates/$candidateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$orgSlug}/artifacts'
    | '/{-$orgSlug}/policies'
    | '/{-$orgSlug}/secrets'
    | '/{-$orgSlug}/skills'
    | '/{-$orgSlug}/toolkits'
    | '/{-$orgSlug}/tools'
    | '/{-$orgSlug}'
    | '/{-$orgSlug}/artifacts/$artifactId'
    | '/{-$orgSlug}/connect/$integrationSlug'
    | '/{-$orgSlug}/integrations/$namespace'
    | '/{-$orgSlug}/integrations/browse'
    | '/{-$orgSlug}/resume/$executionId'
    | '/{-$orgSlug}/skills/$skillId'
    | '/{-$orgSlug}/skills/new'
    | '/{-$orgSlug}/toolkits/$toolkitSlug'
    | '/{-$orgSlug}/integrations/add/$pluginKey'
    | '/{-$orgSlug}/plugins/$pluginId/$'
    | '/{-$orgSlug}/skills/$skillId/edit'
    | '/{-$orgSlug}/skills/$skillId/updates/$candidateId'
  id:
    | '__root__'
    | '/{-$orgSlug}/artifacts'
    | '/{-$orgSlug}/policies'
    | '/{-$orgSlug}/secrets'
    | '/{-$orgSlug}/skills'
    | '/{-$orgSlug}/toolkits'
    | '/{-$orgSlug}/tools'
    | '/{-$orgSlug}/'
    | '/{-$orgSlug}/artifacts/$artifactId'
    | '/{-$orgSlug}/connect/$integrationSlug'
    | '/{-$orgSlug}/integrations/$namespace'
    | '/{-$orgSlug}/integrations/browse'
    | '/{-$orgSlug}/resume/$executionId'
    | '/{-$orgSlug}/skills/$skillId'
    | '/{-$orgSlug}/skills/new'
    | '/{-$orgSlug}/toolkits/$toolkitSlug'
    | '/{-$orgSlug}/integrations/add/$pluginKey'
    | '/{-$orgSlug}/plugins/$pluginId/$'
    | '/{-$orgSlug}/skills/$skillId/edit'
    | '/{-$orgSlug}/skills/$skillId/updates/$candidateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DotDotDotDotDotDotReactSrcRoutesArtifactsRoute: typeof DotDotDotDotDotDotReactSrcRoutesArtifactsRouteWithChildren
  DotDotDotDotDotDotReactSrcRoutesPoliciesRoute: typeof DotDotDotDotDotDotReactSrcRoutesPoliciesRoute
  SecretsRoute: typeof SecretsRoute
  DotDotDotDotDotDotReactSrcRoutesSkillsRoute: typeof DotDotDotDotDotDotReactSrcRoutesSkillsRouteWithChildren
  DotDotDotDotDotDotReactSrcRoutesToolkitsRoute: typeof DotDotDotDotDotDotReactSrcRoutesToolkitsRouteWithChildren
  DotDotDotDotDotDotReactSrcRoutesToolsRoute: typeof DotDotDotDotDotDotReactSrcRoutesToolsRoute
  DotDotDotDotDotDotReactSrcRoutesIndexRoute: typeof DotDotDotDotDotDotReactSrcRoutesIndexRoute
  DotDotDotDotDotDotReactSrcRoutesConnectDotintegrationSlugRoute: typeof DotDotDotDotDotDotReactSrcRoutesConnectDotintegrationSlugRoute
  DotDotDotDotDotDotReactSrcRoutesIntegrationsDotnamespaceRoute: typeof DotDotDotDotDotDotReactSrcRoutesIntegrationsDotnamespaceRoute
  DotDotDotDotDotDotReactSrcRoutesIntegrationsDotbrowseRoute: typeof DotDotDotDotDotDotReactSrcRoutesIntegrationsDotbrowseRoute
  DotDotDotDotDotDotReactSrcRoutesResumeDotexecutionIdRoute: typeof DotDotDotDotDotDotReactSrcRoutesResumeDotexecutionIdRoute
  DotDotDotDotDotDotReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute: typeof DotDotDotDotDotDotReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute
  DotDotDotDotDotDotReactSrcRoutesPluginsDotpluginIdDotsplatRoute: typeof DotDotDotDotDotDotReactSrcRoutesPluginsDotpluginIdDotsplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$orgSlug}/': {
      id: '/{-$orgSlug}/'
      path: '/{-$orgSlug}'
      fullPath: '/{-$orgSlug}/'
      preLoaderRoute: typeof DotDotDotDotDotDotReactSrcRoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/tools': {
      id: '/{-$orgSlug}/tools'
      path: '/{-$orgSlug}/tools'
      fullPath: '/{-$orgSlug}/tools'
      preLoaderRoute: typeof DotDotDotDotDotDotReactSrcRoutesToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/toolkits': {
      id: '/{-$orgSlug}/toolkits'
      path: '/{-$orgSlug}/toolkits'
      fullPath: '/{-$orgSlug}/toolkits'
      preLoaderRoute: typeof DotDotDotDotDotDotReactSrcRoutesToolkitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/skills': {
      id: '/{-$orgSlug}/skills'
      path: '/{-$orgSlug}/skills'
      fullPath: '/{-$orgSlug}/skills'
      preLoaderRoute: typeof DotDotDotDotDotDotReactSrcRoutesSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/secrets': {
      id: '/{-$orgSlug}/secrets'
      path: '/{-$orgSlug}/secrets'
      fullPath: '/{-$orgSlug}/secrets'
      preLoaderRoute: typeof SecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/policies': {
      id: '/{-$orgSlug}/policies'
      path: '/{-$orgSlug}/policies'
      fullPath: '/{-$orgSlug}/policies'
      preLoaderRoute: typeof DotDotDotDotDotDotReactSrcRoutesPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/artifacts': {
      id: '/{-$orgSlug}/artifacts'
      path: '/{-$orgSlug}/artifacts'
      fullPath: '/{-$orgSlug}/artifacts'
      preLoaderRoute: typeof DotDotDotDotDotDotReactSrcRoutesArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/toolkits/$toolkitSlug': {
      id: '/{-$orgSlug}/toolkits/$toolkitSlug'
      path: '/$toolkitSlug'
      fullPath: '/{-$orgSlug}/toolkits/$toolkitSlug'
      preLoaderRoute: typeof DotDotDotDotDotDotReactSrcRoutesToolkitsDottoolkitSlugRouteImport
      parentRoute: typeof DotDotDotDotDotDotReactSrcRoutesToolkitsRoute
    }
    '/{-$orgSlug}/skills/new': {
      id: '/{-$orgSlug}/skills/new'
      path: '/new'
      fullPath: '/{-$orgSlug}/skills/new'
      preLoaderRoute: typeof DotDotDotDotDotDotReactSrcRoutesSkillsDotnewRouteImport
      parentRoute: typeof DotDotDotDotDotDotReactSrcRoutesSkillsRoute
    }
    '/{-$orgSlug}/skills/$skillId': {
      id: '/{-$orgSlug}/skills/$skillId'
      path: '/$skillId'
      fullPath: '/{-$orgSlug}/skills/$skillId'
      preLoaderRoute: typeof DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdRouteImport
      parentRoute: typeof DotDotDotDotDotDotReactSrcRoutesSkillsRoute
    }
    '/{-$orgSlug}/resume/$executionId': {
      id: '/{-$orgSlug}/resume/$executionId'
      path: '/{-$orgSlug}/resume/$executionId'
      fullPath: '/{-$orgSlug}/resume/$executionId'
      preLoaderRoute: typeof DotDotDotDotDotDotReactSrcRoutesResumeDotexecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/integrations/browse': {
      id: '/{-$orgSlug}/integrations/browse'
      path: '/{-$orgSlug}/integrations/browse'
      fullPath: '/{-$orgSlug}/integrations/browse'
      preLoaderRoute: typeof DotDotDotDotDotDotReactSrcRoutesIntegrationsDotbrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/integrations/$namespace': {
      id: '/{-$orgSlug}/integrations/$namespace'
      path: '/{-$orgSlug}/integrations/$namespace'
      fullPath: '/{-$orgSlug}/integrations/$namespace'
      preLoaderRoute: typeof DotDotDotDotDotDotReactSrcRoutesIntegrationsDotnamespaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/connect/$integrationSlug': {
      id: '/{-$orgSlug}/connect/$integrationSlug'
      path: '/{-$orgSlug}/connect/$integrationSlug'
      fullPath: '/{-$orgSlug}/connect/$integrationSlug'
      preLoaderRoute: typeof DotDotDotDotDotDotReactSrcRoutesConnectDotintegrationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/artifacts/$artifactId': {
      id: '/{-$orgSlug}/artifacts/$artifactId'
      path: '/$artifactId'
      fullPath: '/{-$orgSlug}/artifacts/$artifactId'
      preLoaderRoute: typeof DotDotDotDotDotDotReactSrcRoutesArtifactsDotartifactIdRouteImport
      parentRoute: typeof DotDotDotDotDotDotReactSrcRoutesArtifactsRoute
    }
    '/{-$orgSlug}/skills/$skillId/edit': {
      id: '/{-$orgSlug}/skills/$skillId/edit'
      path: '/edit'
      fullPath: '/{-$orgSlug}/skills/$skillId/edit'
      preLoaderRoute: typeof DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdDoteditRouteImport
      parentRoute: typeof DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdRoute
    }
    '/{-$orgSlug}/plugins/$pluginId/$': {
      id: '/{-$orgSlug}/plugins/$pluginId/$'
      path: '/{-$orgSlug}/plugins/$pluginId/$'
      fullPath: '/{-$orgSlug}/plugins/$pluginId/$'
      preLoaderRoute: typeof DotDotDotDotDotDotReactSrcRoutesPluginsDotpluginIdDotsplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/integrations/add/$pluginKey': {
      id: '/{-$orgSlug}/integrations/add/$pluginKey'
      path: '/{-$orgSlug}/integrations/add/$pluginKey'
      fullPath: '/{-$orgSlug}/integrations/add/$pluginKey'
      preLoaderRoute: typeof DotDotDotDotDotDotReactSrcRoutesIntegrationsDotaddDotpluginKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/skills/$skillId/updates/$candidateId': {
      id: '/{-$orgSlug}/skills/$skillId/updates/$candidateId'
      path: '/updates/$candidateId'
      fullPath: '/{-$orgSlug}/skills/$skillId/updates/$candidateId'
      preLoaderRoute: typeof DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdDotupdatesDotcandidateIdRouteImport
      parentRoute: typeof DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdRoute
    }
  }
}

interface DotDotDotDotDotDotReactSrcRoutesArtifactsRouteChildren {
  DotDotDotDotDotDotReactSrcRoutesArtifactsDotartifactIdRoute: typeof DotDotDotDotDotDotReactSrcRoutesArtifactsDotartifactIdRoute
}

const DotDotDotDotDotDotReactSrcRoutesArtifactsRouteChildren: DotDotDotDotDotDotReactSrcRoutesArtifactsRouteChildren =
  {
    DotDotDotDotDotDotReactSrcRoutesArtifactsDotartifactIdRoute:
      DotDotDotDotDotDotReactSrcRoutesArtifactsDotartifactIdRoute,
  }

const DotDotDotDotDotDotReactSrcRoutesArtifactsRouteWithChildren =
  DotDotDotDotDotDotReactSrcRoutesArtifactsRoute._addFileChildren(
    DotDotDotDotDotDotReactSrcRoutesArtifactsRouteChildren,
  )

interface DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdRouteChildren {
  DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdDoteditRoute: typeof DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdDoteditRoute
  DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdDotupdatesDotcandidateIdRoute: typeof DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdDotupdatesDotcandidateIdRoute
}

const DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdRouteChildren: DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdRouteChildren =
  {
    DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdDoteditRoute:
      DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdDoteditRoute,
    DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdDotupdatesDotcandidateIdRoute:
      DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdDotupdatesDotcandidateIdRoute,
  }

const DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdRouteWithChildren =
  DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdRoute._addFileChildren(
    DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdRouteChildren,
  )

interface DotDotDotDotDotDotReactSrcRoutesSkillsRouteChildren {
  DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdRoute: typeof DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdRouteWithChildren
  DotDotDotDotDotDotReactSrcRoutesSkillsDotnewRoute: typeof DotDotDotDotDotDotReactSrcRoutesSkillsDotnewRoute
}

const DotDotDotDotDotDotReactSrcRoutesSkillsRouteChildren: DotDotDotDotDotDotReactSrcRoutesSkillsRouteChildren =
  {
    DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdRoute:
      DotDotDotDotDotDotReactSrcRoutesSkillsDotskillIdRouteWithChildren,
    DotDotDotDotDotDotReactSrcRoutesSkillsDotnewRoute:
      DotDotDotDotDotDotReactSrcRoutesSkillsDotnewRoute,
  }

const DotDotDotDotDotDotReactSrcRoutesSkillsRouteWithChildren =
  DotDotDotDotDotDotReactSrcRoutesSkillsRoute._addFileChildren(
    DotDotDotDotDotDotReactSrcRoutesSkillsRouteChildren,
  )

interface DotDotDotDotDotDotReactSrcRoutesToolkitsRouteChildren {
  DotDotDotDotDotDotReactSrcRoutesToolkitsDottoolkitSlugRoute: typeof DotDotDotDotDotDotReactSrcRoutesToolkitsDottoolkitSlugRoute
}

const DotDotDotDotDotDotReactSrcRoutesToolkitsRouteChildren: DotDotDotDotDotDotReactSrcRoutesToolkitsRouteChildren =
  {
    DotDotDotDotDotDotReactSrcRoutesToolkitsDottoolkitSlugRoute:
      DotDotDotDotDotDotReactSrcRoutesToolkitsDottoolkitSlugRoute,
  }

const DotDotDotDotDotDotReactSrcRoutesToolkitsRouteWithChildren =
  DotDotDotDotDotDotReactSrcRoutesToolkitsRoute._addFileChildren(
    DotDotDotDotDotDotReactSrcRoutesToolkitsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  DotDotDotDotDotDotReactSrcRoutesArtifactsRoute:
    DotDotDotDotDotDotReactSrcRoutesArtifactsRouteWithChildren,
  DotDotDotDotDotDotReactSrcRoutesPoliciesRoute:
    DotDotDotDotDotDotReactSrcRoutesPoliciesRoute,
  SecretsRoute: SecretsRoute,
  DotDotDotDotDotDotReactSrcRoutesSkillsRoute:
    DotDotDotDotDotDotReactSrcRoutesSkillsRouteWithChildren,
  DotDotDotDotDotDotReactSrcRoutesToolkitsRoute:
    DotDotDotDotDotDotReactSrcRoutesToolkitsRouteWithChildren,
  DotDotDotDotDotDotReactSrcRoutesToolsRoute:
    DotDotDotDotDotDotReactSrcRoutesToolsRoute,
  DotDotDotDotDotDotReactSrcRoutesIndexRoute:
    DotDotDotDotDotDotReactSrcRoutesIndexRoute,
  DotDotDotDotDotDotReactSrcRoutesConnectDotintegrationSlugRoute:
    DotDotDotDotDotDotReactSrcRoutesConnectDotintegrationSlugRoute,
  DotDotDotDotDotDotReactSrcRoutesIntegrationsDotnamespaceRoute:
    DotDotDotDotDotDotReactSrcRoutesIntegrationsDotnamespaceRoute,
  DotDotDotDotDotDotReactSrcRoutesIntegrationsDotbrowseRoute:
    DotDotDotDotDotDotReactSrcRoutesIntegrationsDotbrowseRoute,
  DotDotDotDotDotDotReactSrcRoutesResumeDotexecutionIdRoute:
    DotDotDotDotDotDotReactSrcRoutesResumeDotexecutionIdRoute,
  DotDotDotDotDotDotReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute:
    DotDotDotDotDotDotReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute,
  DotDotDotDotDotDotReactSrcRoutesPluginsDotpluginIdDotsplatRoute:
    DotDotDotDotDotDotReactSrcRoutesPluginsDotpluginIdDotsplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
