/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRouteImport } from './../../../packages/react/src/routes/index'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRouteImport } from './../../../packages/react/src/routes/tools'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRouteImport } from './../../../packages/react/src/routes/toolkits'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsRouteImport } from './../../../packages/react/src/routes/skills'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSecretsRouteImport } from './../../../packages/react/src/routes/secrets'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRouteImport } from './../../../packages/react/src/routes/policies'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsRouteImport } from './../../../packages/react/src/routes/artifacts'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsDottoolkitSlugRouteImport } from './../../../packages/react/src/routes/toolkits.$toolkitSlug'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotnewRouteImport } from './../../../packages/react/src/routes/skills.new'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdRouteImport } from './../../../packages/react/src/routes/skills.$skillId'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesResumeDotexecutionIdRouteImport } from './../../../packages/react/src/routes/resume.$executionId'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotbrowseRouteImport } from './../../../packages/react/src/routes/integrations.browse'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRouteImport } from './../../../packages/react/src/routes/integrations.$namespace'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesConnectDotintegrationSlugRouteImport } from './../../../packages/react/src/routes/connect.$integrationSlug'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsDotartifactIdRouteImport } from './../../../packages/react/src/routes/artifacts.$artifactId'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdDoteditRouteImport } from './../../../packages/react/src/routes/skills.$skillId.edit'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPluginsDotpluginIdDotsplatRouteImport } from './../../../packages/react/src/routes/plugins.$pluginId.$'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRouteImport } from './../../../packages/react/src/routes/integrations.add.$pluginKey'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdDotupdatesDotcandidateIdRouteImport } from './../../../packages/react/src/routes/skills.$skillId.updates.$candidateId'

const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRouteImport.update({
    id: '/{-$orgSlug}/',
    path: '/{-$orgSlug}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRouteImport.update({
    id: '/{-$orgSlug}/tools',
    path: '/{-$orgSlug}/tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRouteImport.update({
    id: '/{-$orgSlug}/toolkits',
    path: '/{-$orgSlug}/toolkits',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsRouteImport.update({
    id: '/{-$orgSlug}/skills',
    path: '/{-$orgSlug}/skills',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSecretsRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSecretsRouteImport.update({
    id: '/{-$orgSlug}/secrets',
    path: '/{-$orgSlug}/secrets',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRouteImport.update({
    id: '/{-$orgSlug}/policies',
    path: '/{-$orgSlug}/policies',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsRouteImport.update({
    id: '/{-$orgSlug}/artifacts',
    path: '/{-$orgSlug}/artifacts',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsDottoolkitSlugRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsDottoolkitSlugRouteImport.update(
    {
      id: '/$toolkitSlug',
      path: '/$toolkitSlug',
      getParentRoute: () =>
        DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRoute,
    } as any,
  )
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotnewRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotnewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () =>
      DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsRoute,
  } as any)
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdRouteImport.update(
    {
      id: '/$skillId',
      path: '/$skillId',
      getParentRoute: () =>
        DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsRoute,
    } as any,
  )
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesResumeDotexecutionIdRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesResumeDotexecutionIdRouteImport.update(
    {
      id: '/{-$orgSlug}/resume/$executionId',
      path: '/{-$orgSlug}/resume/$executionId',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotbrowseRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotbrowseRouteImport.update(
    {
      id: '/{-$orgSlug}/integrations/browse',
      path: '/{-$orgSlug}/integrations/browse',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRouteImport.update(
    {
      id: '/{-$orgSlug}/integrations/$namespace',
      path: '/{-$orgSlug}/integrations/$namespace',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesConnectDotintegrationSlugRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesConnectDotintegrationSlugRouteImport.update(
    {
      id: '/{-$orgSlug}/connect/$integrationSlug',
      path: '/{-$orgSlug}/connect/$integrationSlug',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsDotartifactIdRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsDotartifactIdRouteImport.update(
    {
      id: '/$artifactId',
      path: '/$artifactId',
      getParentRoute: () =>
        DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsRoute,
    } as any,
  )
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdDoteditRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdDoteditRouteImport.update(
    {
      id: '/edit',
      path: '/edit',
      getParentRoute: () =>
        DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdRoute,
    } as any,
  )
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPluginsDotpluginIdDotsplatRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPluginsDotpluginIdDotsplatRouteImport.update(
    {
      id: '/{-$orgSlug}/plugins/$pluginId/$',
      path: '/{-$orgSlug}/plugins/$pluginId/$',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRouteImport.update(
    {
      id: '/{-$orgSlug}/integrations/add/$pluginKey',
      path: '/{-$orgSlug}/integrations/add/$pluginKey',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdDotupdatesDotcandidateIdRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdDotupdatesDotcandidateIdRouteImport.update(
    {
      id: '/updates/$candidateId',
      path: '/updates/$candidateId',
      getParentRoute: () =>
        DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/{-$orgSlug}/artifacts': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsRouteWithChildren
  '/{-$orgSlug}/policies': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute
  '/{-$orgSlug}/secrets': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSecretsRoute
  '/{-$orgSlug}/skills': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsRouteWithChildren
  '/{-$orgSlug}/toolkits': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRouteWithChildren
  '/{-$orgSlug}/tools': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute
  '/{-$orgSlug}/': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute
  '/{-$orgSlug}/artifacts/$artifactId': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsDotartifactIdRoute
  '/{-$orgSlug}/connect/$integrationSlug': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesConnectDotintegrationSlugRoute
  '/{-$orgSlug}/integrations/$namespace': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute
  '/{-$orgSlug}/integrations/browse': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotbrowseRoute
  '/{-$orgSlug}/resume/$executionId': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesResumeDotexecutionIdRoute
  '/{-$orgSlug}/skills/$skillId': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdRouteWithChildren
  '/{-$orgSlug}/skills/new': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotnewRoute
  '/{-$orgSlug}/toolkits/$toolkitSlug': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsDottoolkitSlugRoute
  '/{-$orgSlug}/integrations/add/$pluginKey': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute
  '/{-$orgSlug}/plugins/$pluginId/$': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPluginsDotpluginIdDotsplatRoute
  '/{-$orgSlug}/skills/$skillId/edit': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdDoteditRoute
  '/{-$orgSlug}/skills/$skillId/updates/$candidateId': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdDotupdatesDotcandidateIdRoute
}
export interface FileRoutesByTo {
  '/{-$orgSlug}/artifacts': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsRouteWithChildren
  '/{-$orgSlug}/policies': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute
  '/{-$orgSlug}/secrets': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSecretsRoute
  '/{-$orgSlug}/skills': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsRouteWithChildren
  '/{-$orgSlug}/toolkits': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRouteWithChildren
  '/{-$orgSlug}/tools': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute
  '/{-$orgSlug}': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute
  '/{-$orgSlug}/artifacts/$artifactId': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsDotartifactIdRoute
  '/{-$orgSlug}/connect/$integrationSlug': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesConnectDotintegrationSlugRoute
  '/{-$orgSlug}/integrations/$namespace': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute
  '/{-$orgSlug}/integrations/browse': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotbrowseRoute
  '/{-$orgSlug}/resume/$executionId': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesResumeDotexecutionIdRoute
  '/{-$orgSlug}/skills/$skillId': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdRouteWithChildren
  '/{-$orgSlug}/skills/new': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotnewRoute
  '/{-$orgSlug}/toolkits/$toolkitSlug': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsDottoolkitSlugRoute
  '/{-$orgSlug}/integrations/add/$pluginKey': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute
  '/{-$orgSlug}/plugins/$pluginId/$': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPluginsDotpluginIdDotsplatRoute
  '/{-$orgSlug}/skills/$skillId/edit': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdDoteditRoute
  '/{-$orgSlug}/skills/$skillId/updates/$candidateId': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdDotupdatesDotcandidateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$orgSlug}/artifacts': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsRouteWithChildren
  '/{-$orgSlug}/policies': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute
  '/{-$orgSlug}/secrets': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSecretsRoute
  '/{-$orgSlug}/skills': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsRouteWithChildren
  '/{-$orgSlug}/toolkits': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRouteWithChildren
  '/{-$orgSlug}/tools': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute
  '/{-$orgSlug}/': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute
  '/{-$orgSlug}/artifacts/$artifactId': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsDotartifactIdRoute
  '/{-$orgSlug}/connect/$integrationSlug': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesConnectDotintegrationSlugRoute
  '/{-$orgSlug}/integrations/$namespace': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute
  '/{-$orgSlug}/integrations/browse': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotbrowseRoute
  '/{-$orgSlug}/resume/$executionId': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesResumeDotexecutionIdRoute
  '/{-$orgSlug}/skills/$skillId': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdRouteWithChildren
  '/{-$orgSlug}/skills/new': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotnewRoute
  '/{-$orgSlug}/toolkits/$toolkitSlug': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsDottoolkitSlugRoute
  '/{-$orgSlug}/integrations/add/$pluginKey': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute
  '/{-$orgSlug}/plugins/$pluginId/$': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPluginsDotpluginIdDotsplatRoute
  '/{-$orgSlug}/skills/$skillId/edit': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdDoteditRoute
  '/{-$orgSlug}/skills/$skillId/updates/$candidateId': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdDotupdatesDotcandidateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$orgSlug}/artifacts'
    | '/{-$orgSlug}/policies'
    | '/{-$orgSlug}/secrets'
    | '/{-$orgSlug}/skills'
    | '/{-$orgSlug}/toolkits'
    | '/{-$orgSlug}/tools'
    | '/{-$orgSlug}/'
    | '/{-$orgSlug}/artifacts/$artifactId'
    | '/{-$orgSlug}/connect/$integrationSlug'
    | '/{-$orgSlug}/integrations/$namespace'
    | '/{-$orgSlug}/integrations/browse'
    | '/{-$orgSlug}/resume/$executionId'
    | '/{-$orgSlug}/skills/$skillId'
    | '/{-$orgSlug}/skills/new'
    | '/{-$orgSlug}/toolkits/$toolkitSlug'
    | '/{-$orgSlug}/integrations/add/$pluginKey'
    | '/{-$orgSlug}/plugins/$pluginId/$'
    | '/{-$orgSlug}/skills/$skillId/edit'
    | '/{-$orgSlug}/skills/$skillId/updates/$candidateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$orgSlug}/artifacts'
    | '/{-$orgSlug}/policies'
    | '/{-$orgSlug}/secrets'
    | '/{-$orgSlug}/skills'
    | '/{-$orgSlug}/toolkits'
    | '/{-$orgSlug}/tools'
    | '/{-$orgSlug}'
    | '/{-$orgSlug}/artifacts/$artifactId'
    | '/{-$orgSlug}/connect/$integrationSlug'
    | '/{-$orgSlug}/integrations/$namespace'
    | '/{-$orgSlug}/integrations/browse'
    | '/{-$orgSlug}/resume/$executionId'
    | '/{-$orgSlug}/skills/$skillId'
    | '/{-$orgSlug}/skills/new'
    | '/{-$orgSlug}/toolkits/$toolkitSlug'
    | '/{-$orgSlug}/integrations/add/$pluginKey'
    | '/{-$orgSlug}/plugins/$pluginId/$'
    | '/{-$orgSlug}/skills/$skillId/edit'
    | '/{-$orgSlug}/skills/$skillId/updates/$candidateId'
  id:
    | '__root__'
    | '/{-$orgSlug}/artifacts'
    | '/{-$orgSlug}/policies'
    | '/{-$orgSlug}/secrets'
    | '/{-$orgSlug}/skills'
    | '/{-$orgSlug}/toolkits'
    | '/{-$orgSlug}/tools'
    | '/{-$orgSlug}/'
    | '/{-$orgSlug}/artifacts/$artifactId'
    | '/{-$orgSlug}/connect/$integrationSlug'
    | '/{-$orgSlug}/integrations/$namespace'
    | '/{-$orgSlug}/integrations/browse'
    | '/{-$orgSlug}/resume/$executionId'
    | '/{-$orgSlug}/skills/$skillId'
    | '/{-$orgSlug}/skills/new'
    | '/{-$orgSlug}/toolkits/$toolkitSlug'
    | '/{-$orgSlug}/integrations/add/$pluginKey'
    | '/{-$orgSlug}/plugins/$pluginId/$'
    | '/{-$orgSlug}/skills/$skillId/edit'
    | '/{-$orgSlug}/skills/$skillId/updates/$candidateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsRouteWithChildren
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSecretsRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSecretsRoute
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsRouteWithChildren
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRouteWithChildren
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesConnectDotintegrationSlugRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesConnectDotintegrationSlugRoute
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotbrowseRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotbrowseRoute
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesResumeDotexecutionIdRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesResumeDotexecutionIdRoute
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPluginsDotpluginIdDotsplatRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPluginsDotpluginIdDotsplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$orgSlug}/': {
      id: '/{-$orgSlug}/'
      path: '/{-$orgSlug}'
      fullPath: '/{-$orgSlug}/'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/tools': {
      id: '/{-$orgSlug}/tools'
      path: '/{-$orgSlug}/tools'
      fullPath: '/{-$orgSlug}/tools'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/toolkits': {
      id: '/{-$orgSlug}/toolkits'
      path: '/{-$orgSlug}/toolkits'
      fullPath: '/{-$orgSlug}/toolkits'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/skills': {
      id: '/{-$orgSlug}/skills'
      path: '/{-$orgSlug}/skills'
      fullPath: '/{-$orgSlug}/skills'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/secrets': {
      id: '/{-$orgSlug}/secrets'
      path: '/{-$orgSlug}/secrets'
      fullPath: '/{-$orgSlug}/secrets'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/policies': {
      id: '/{-$orgSlug}/policies'
      path: '/{-$orgSlug}/policies'
      fullPath: '/{-$orgSlug}/policies'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/artifacts': {
      id: '/{-$orgSlug}/artifacts'
      path: '/{-$orgSlug}/artifacts'
      fullPath: '/{-$orgSlug}/artifacts'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/toolkits/$toolkitSlug': {
      id: '/{-$orgSlug}/toolkits/$toolkitSlug'
      path: '/$toolkitSlug'
      fullPath: '/{-$orgSlug}/toolkits/$toolkitSlug'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsDottoolkitSlugRouteImport
      parentRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRoute
    }
    '/{-$orgSlug}/skills/new': {
      id: '/{-$orgSlug}/skills/new'
      path: '/new'
      fullPath: '/{-$orgSlug}/skills/new'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotnewRouteImport
      parentRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsRoute
    }
    '/{-$orgSlug}/skills/$skillId': {
      id: '/{-$orgSlug}/skills/$skillId'
      path: '/$skillId'
      fullPath: '/{-$orgSlug}/skills/$skillId'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdRouteImport
      parentRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsRoute
    }
    '/{-$orgSlug}/resume/$executionId': {
      id: '/{-$orgSlug}/resume/$executionId'
      path: '/{-$orgSlug}/resume/$executionId'
      fullPath: '/{-$orgSlug}/resume/$executionId'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesResumeDotexecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/integrations/browse': {
      id: '/{-$orgSlug}/integrations/browse'
      path: '/{-$orgSlug}/integrations/browse'
      fullPath: '/{-$orgSlug}/integrations/browse'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotbrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/integrations/$namespace': {
      id: '/{-$orgSlug}/integrations/$namespace'
      path: '/{-$orgSlug}/integrations/$namespace'
      fullPath: '/{-$orgSlug}/integrations/$namespace'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/connect/$integrationSlug': {
      id: '/{-$orgSlug}/connect/$integrationSlug'
      path: '/{-$orgSlug}/connect/$integrationSlug'
      fullPath: '/{-$orgSlug}/connect/$integrationSlug'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesConnectDotintegrationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/artifacts/$artifactId': {
      id: '/{-$orgSlug}/artifacts/$artifactId'
      path: '/$artifactId'
      fullPath: '/{-$orgSlug}/artifacts/$artifactId'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsDotartifactIdRouteImport
      parentRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsRoute
    }
    '/{-$orgSlug}/skills/$skillId/edit': {
      id: '/{-$orgSlug}/skills/$skillId/edit'
      path: '/edit'
      fullPath: '/{-$orgSlug}/skills/$skillId/edit'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdDoteditRouteImport
      parentRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdRoute
    }
    '/{-$orgSlug}/plugins/$pluginId/$': {
      id: '/{-$orgSlug}/plugins/$pluginId/$'
      path: '/{-$orgSlug}/plugins/$pluginId/$'
      fullPath: '/{-$orgSlug}/plugins/$pluginId/$'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPluginsDotpluginIdDotsplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/integrations/add/$pluginKey': {
      id: '/{-$orgSlug}/integrations/add/$pluginKey'
      path: '/{-$orgSlug}/integrations/add/$pluginKey'
      fullPath: '/{-$orgSlug}/integrations/add/$pluginKey'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/skills/$skillId/updates/$candidateId': {
      id: '/{-$orgSlug}/skills/$skillId/updates/$candidateId'
      path: '/updates/$candidateId'
      fullPath: '/{-$orgSlug}/skills/$skillId/updates/$candidateId'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdDotupdatesDotcandidateIdRouteImport
      parentRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdRoute
    }
  }
}

interface DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsRouteChildren {
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsDotartifactIdRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsDotartifactIdRoute
}

const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsRouteChildren: DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsRouteChildren =
  {
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsDotartifactIdRoute:
      DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsDotartifactIdRoute,
  }

const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsRouteWithChildren =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsRoute._addFileChildren(
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsRouteChildren,
  )

interface DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdRouteChildren {
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdDoteditRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdDoteditRoute
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdDotupdatesDotcandidateIdRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdDotupdatesDotcandidateIdRoute
}

const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdRouteChildren: DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdRouteChildren =
  {
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdDoteditRoute:
      DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdDoteditRoute,
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdDotupdatesDotcandidateIdRoute:
      DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdDotupdatesDotcandidateIdRoute,
  }

const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdRouteWithChildren =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdRoute._addFileChildren(
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdRouteChildren,
  )

interface DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsRouteChildren {
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdRouteWithChildren
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotnewRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotnewRoute
}

const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsRouteChildren: DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsRouteChildren =
  {
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdRoute:
      DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotskillIdRouteWithChildren,
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotnewRoute:
      DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsDotnewRoute,
  }

const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsRouteWithChildren =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsRoute._addFileChildren(
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsRouteChildren,
  )

interface DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRouteChildren {
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsDottoolkitSlugRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsDottoolkitSlugRoute
}

const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRouteChildren: DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRouteChildren =
  {
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsDottoolkitSlugRoute:
      DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsDottoolkitSlugRoute,
  }

const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRouteWithChildren =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRoute._addFileChildren(
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesArtifactsRouteWithChildren,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSecretsRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSecretsRoute,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesSkillsRouteWithChildren,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRouteWithChildren,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesConnectDotintegrationSlugRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesConnectDotintegrationSlugRoute,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotbrowseRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotbrowseRoute,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesResumeDotexecutionIdRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesResumeDotexecutionIdRoute,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPluginsDotpluginIdDotsplatRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPluginsDotpluginIdDotsplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
