/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRouteImport } from './../../../packages/react/src/routes/index'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRouteImport } from './../../../packages/react/src/routes/tools'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRouteImport } from './../../../packages/react/src/routes/toolkits'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRouteImport } from './../../../packages/react/src/routes/policies'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesCredentialsRouteImport } from './../../../packages/react/src/routes/credentials'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsDottoolkitSlugRouteImport } from './../../../packages/react/src/routes/toolkits.$toolkitSlug'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesResumeDotexecutionIdRouteImport } from './../../../packages/react/src/routes/resume.$executionId'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRouteImport } from './../../../packages/react/src/routes/integrations.$namespace'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPluginsDotpluginIdDotsplatRouteImport } from './../../../packages/react/src/routes/plugins.$pluginId.$'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRouteImport } from './../../../packages/react/src/routes/integrations.add.$pluginKey'

const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRouteImport.update({
    id: '/{-$orgSlug}/',
    path: '/{-$orgSlug}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRouteImport.update({
    id: '/{-$orgSlug}/tools',
    path: '/{-$orgSlug}/tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRouteImport.update({
    id: '/{-$orgSlug}/toolkits',
    path: '/{-$orgSlug}/toolkits',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRouteImport.update({
    id: '/{-$orgSlug}/policies',
    path: '/{-$orgSlug}/policies',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesCredentialsRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesCredentialsRouteImport.update({
    id: '/{-$orgSlug}/credentials',
    path: '/{-$orgSlug}/credentials',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsDottoolkitSlugRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsDottoolkitSlugRouteImport.update(
    {
      id: '/$toolkitSlug',
      path: '/$toolkitSlug',
      getParentRoute: () =>
        DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRoute,
    } as any,
  )
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesResumeDotexecutionIdRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesResumeDotexecutionIdRouteImport.update(
    {
      id: '/{-$orgSlug}/resume/$executionId',
      path: '/{-$orgSlug}/resume/$executionId',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRouteImport.update(
    {
      id: '/{-$orgSlug}/integrations/$namespace',
      path: '/{-$orgSlug}/integrations/$namespace',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPluginsDotpluginIdDotsplatRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPluginsDotpluginIdDotsplatRouteImport.update(
    {
      id: '/{-$orgSlug}/plugins/$pluginId/$',
      path: '/{-$orgSlug}/plugins/$pluginId/$',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRouteImport.update(
    {
      id: '/{-$orgSlug}/integrations/add/$pluginKey',
      path: '/{-$orgSlug}/integrations/add/$pluginKey',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/{-$orgSlug}/credentials': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesCredentialsRoute
  '/{-$orgSlug}/policies': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute
  '/{-$orgSlug}/toolkits': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRouteWithChildren
  '/{-$orgSlug}/tools': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute
  '/{-$orgSlug}/': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute
  '/{-$orgSlug}/integrations/$namespace': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute
  '/{-$orgSlug}/resume/$executionId': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesResumeDotexecutionIdRoute
  '/{-$orgSlug}/toolkits/$toolkitSlug': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsDottoolkitSlugRoute
  '/{-$orgSlug}/integrations/add/$pluginKey': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute
  '/{-$orgSlug}/plugins/$pluginId/$': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPluginsDotpluginIdDotsplatRoute
}
export interface FileRoutesByTo {
  '/{-$orgSlug}/credentials': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesCredentialsRoute
  '/{-$orgSlug}/policies': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute
  '/{-$orgSlug}/toolkits': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRouteWithChildren
  '/{-$orgSlug}/tools': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute
  '/{-$orgSlug}': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute
  '/{-$orgSlug}/integrations/$namespace': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute
  '/{-$orgSlug}/resume/$executionId': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesResumeDotexecutionIdRoute
  '/{-$orgSlug}/toolkits/$toolkitSlug': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsDottoolkitSlugRoute
  '/{-$orgSlug}/integrations/add/$pluginKey': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute
  '/{-$orgSlug}/plugins/$pluginId/$': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPluginsDotpluginIdDotsplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$orgSlug}/credentials': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesCredentialsRoute
  '/{-$orgSlug}/policies': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute
  '/{-$orgSlug}/toolkits': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRouteWithChildren
  '/{-$orgSlug}/tools': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute
  '/{-$orgSlug}/': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute
  '/{-$orgSlug}/integrations/$namespace': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute
  '/{-$orgSlug}/resume/$executionId': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesResumeDotexecutionIdRoute
  '/{-$orgSlug}/toolkits/$toolkitSlug': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsDottoolkitSlugRoute
  '/{-$orgSlug}/integrations/add/$pluginKey': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute
  '/{-$orgSlug}/plugins/$pluginId/$': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPluginsDotpluginIdDotsplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$orgSlug}/credentials'
    | '/{-$orgSlug}/policies'
    | '/{-$orgSlug}/toolkits'
    | '/{-$orgSlug}/tools'
    | '/{-$orgSlug}/'
    | '/{-$orgSlug}/integrations/$namespace'
    | '/{-$orgSlug}/resume/$executionId'
    | '/{-$orgSlug}/toolkits/$toolkitSlug'
    | '/{-$orgSlug}/integrations/add/$pluginKey'
    | '/{-$orgSlug}/plugins/$pluginId/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$orgSlug}/credentials'
    | '/{-$orgSlug}/policies'
    | '/{-$orgSlug}/toolkits'
    | '/{-$orgSlug}/tools'
    | '/{-$orgSlug}'
    | '/{-$orgSlug}/integrations/$namespace'
    | '/{-$orgSlug}/resume/$executionId'
    | '/{-$orgSlug}/toolkits/$toolkitSlug'
    | '/{-$orgSlug}/integrations/add/$pluginKey'
    | '/{-$orgSlug}/plugins/$pluginId/$'
  id:
    | '__root__'
    | '/{-$orgSlug}/credentials'
    | '/{-$orgSlug}/policies'
    | '/{-$orgSlug}/toolkits'
    | '/{-$orgSlug}/tools'
    | '/{-$orgSlug}/'
    | '/{-$orgSlug}/integrations/$namespace'
    | '/{-$orgSlug}/resume/$executionId'
    | '/{-$orgSlug}/toolkits/$toolkitSlug'
    | '/{-$orgSlug}/integrations/add/$pluginKey'
    | '/{-$orgSlug}/plugins/$pluginId/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesCredentialsRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesCredentialsRoute
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRouteWithChildren
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesResumeDotexecutionIdRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesResumeDotexecutionIdRoute
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPluginsDotpluginIdDotsplatRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPluginsDotpluginIdDotsplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$orgSlug}/': {
      id: '/{-$orgSlug}/'
      path: '/{-$orgSlug}'
      fullPath: '/{-$orgSlug}/'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/tools': {
      id: '/{-$orgSlug}/tools'
      path: '/{-$orgSlug}/tools'
      fullPath: '/{-$orgSlug}/tools'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/toolkits': {
      id: '/{-$orgSlug}/toolkits'
      path: '/{-$orgSlug}/toolkits'
      fullPath: '/{-$orgSlug}/toolkits'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/policies': {
      id: '/{-$orgSlug}/policies'
      path: '/{-$orgSlug}/policies'
      fullPath: '/{-$orgSlug}/policies'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/credentials': {
      id: '/{-$orgSlug}/credentials'
      path: '/{-$orgSlug}/credentials'
      fullPath: '/{-$orgSlug}/credentials'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/toolkits/$toolkitSlug': {
      id: '/{-$orgSlug}/toolkits/$toolkitSlug'
      path: '/$toolkitSlug'
      fullPath: '/{-$orgSlug}/toolkits/$toolkitSlug'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsDottoolkitSlugRouteImport
      parentRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRoute
    }
    '/{-$orgSlug}/resume/$executionId': {
      id: '/{-$orgSlug}/resume/$executionId'
      path: '/{-$orgSlug}/resume/$executionId'
      fullPath: '/{-$orgSlug}/resume/$executionId'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesResumeDotexecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/integrations/$namespace': {
      id: '/{-$orgSlug}/integrations/$namespace'
      path: '/{-$orgSlug}/integrations/$namespace'
      fullPath: '/{-$orgSlug}/integrations/$namespace'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/plugins/$pluginId/$': {
      id: '/{-$orgSlug}/plugins/$pluginId/$'
      path: '/{-$orgSlug}/plugins/$pluginId/$'
      fullPath: '/{-$orgSlug}/plugins/$pluginId/$'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPluginsDotpluginIdDotsplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$orgSlug}/integrations/add/$pluginKey': {
      id: '/{-$orgSlug}/integrations/add/$pluginKey'
      path: '/{-$orgSlug}/integrations/add/$pluginKey'
      fullPath: '/{-$orgSlug}/integrations/add/$pluginKey'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRouteChildren {
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsDottoolkitSlugRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsDottoolkitSlugRoute
}

const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRouteChildren: DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRouteChildren =
  {
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsDottoolkitSlugRoute:
      DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsDottoolkitSlugRoute,
  }

const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRouteWithChildren =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRoute._addFileChildren(
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesCredentialsRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesCredentialsRoute,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolkitsRouteWithChildren,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesResumeDotexecutionIdRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesResumeDotexecutionIdRoute,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPluginsDotpluginIdDotsplatRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPluginsDotpluginIdDotsplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
