/** Compile-time checks for the author contract; the callbacks are never executed. */
import {
  type QueryContext,
  type MutationContext,
  defineDatabase,
  table,
  object,
  string,
  number,
  boolean,
  json,
} from "../src/index.ts";
const database = defineDatabase({
  messages: table({
    body: string(),
    score: number().optional(),
    category: string().optional().default("inbox"),
    read: boolean().default(false),
  }).index("by_body", ["body"]),
});

const requirements = { accounts: {}, database };

query({ input: object({}), output: json() }, async ({ db }: QueryContext<typeof requirements>) => {
  db.messages.withIndex("by_body", (q) => q.eq("body", "hello"));
  // @ts-expect-error Only declared indexes and by_creation exist.
  db.messages.withIndex("typo");
  // @ts-expect-error Index fields retain their scalar types.
  db.messages.withIndex("by_body", (q) => q.eq("body", 10));
  // @ts-expect-error Queries have no write capability.
  await db.messages.insert({ body: "hello" });
  return [];
});
mutation(
  { input: object({}), output: json() },
  async ({ db }: MutationContext<typeof requirements>) => {
    await db.messages.insert({ body: "hello" });
    await db.messages.insert({ body: "hello", score: null });
    await db.messages.insert({ body: "hello", score: undefined });
    await db.messages.insert({ body: "hello", category: null });
    // @ts-expect-error Required columns cannot be omitted.
    await db.messages.insert({});
    // @ts-expect-error Row metadata is generated by the host.
    await db.messages.insert({ body: "hello", id: "chosen" });
    // @ts-expect-error Stored column types are retained for patches.
    await db.messages.update("row", { body: 123 });
    return [];
  },
);

// External operations use the same references and infer input/output without a database.
import { query, mutation, withApproval } from "../src/index.ts";
import { queryReference, mutationReference } from "../src/client.ts";
const externalRead = query({ input: object({ name: string() }) }, async (_, input) => input.name);
const externalWrite = mutation(
  { input: object({ count: number() }) },
  async (_, input) => input.count,
);
const guarded = withApproval(externalWrite, ({ toolInput }) =>
  toolInput.count > 10 ? "user-approval" : "approved",
);
queryReference<typeof externalRead>("read");
mutationReference<typeof guarded>("write");
// @ts-expect-error A mutation must never be mounted as a reactive query.
queryReference<typeof externalWrite>("write");
// @ts-expect-error Query and mutation references keep distinct capabilities.
mutationReference<typeof externalRead>("read");
