// Generated by packages/app-templates/scripts/executor-intro.ts. Do not edit.

/** SHA-256 of each file the Executor app publishes as a skill, keyed by `<skill>/<file>`. */
export const executorSkillDigests: Readonly<Record<string, string>> = {
  "app-authoring/SKILL.md": "350200a92d4499060fa0b4facee96de4ffdd86d64487c27c9ad3c5466821354a",
  "app-authoring/accounts.md": "b3897072d03fef9a15711f1c24a43e90375fb02072d14127b74ad38634730287",
  "app-authoring/deploy.md": "7930a103f95367e79b19fbf8b69f281d75611faa63aa8b2482b3e81b22611e20",
  "app-authoring/events.md": "202bde87c2320af9706828063c6aaeeac0c9b8661971f610220f2a49293e3561",
  "app-authoring/integrations.md": "75b9833337a7c4f74e944b99de17f781304e0c5e65898bd10d40ee49d8986ac8",
  "app-authoring/starter.md": "3e5b2f55da9aed2a6c0ff95d4c1982d1da6aa206fd404d6b5f1fb0b7c2880077",
  "app-authoring/storage.md": "da2f45549232df5adc778e37d57ae0d4e31a4c864361fb19c6b2fe2e10c64090",
  "app-authoring/tools.md": "f1f39f7b536a1ae3d35b6300f5bc19f781a63775c324d18c6dfe4d2e2cb43bc4",
  "app-authoring/ui.md": "ac9751f5f45b0196e46e1deffa09cb302c7e43099bcc247ec455f8808b539542",
  "app-authoring/webhooks.md": "b7f43ad7af7fe1093cdc957cdec5f43bc98115d3c3237af1788cdd68d7fd9fce",
  "app-authoring/workflows.md": "9e517eaf6f461ac07fd2d29a03f0d545e79cfcbcfedbed5b8432e7b41392257b",
  "code-mode/SKILL.md": "18371ae9b6c6a49b47587361ff84b9b4c44ab26b87bdae29a77debbc102d2e7a",
  "executor/SKILL.md": "580e2e296e8665c950d41197e4bf2df639be12f6ee3ec8ce51d27129dd0774ff",
  "executor/feedback.md": "11397bd260917e5a21e92897a19368d0426bf5944a7c081adc2c061d1ea797cd"
};
