/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrgRouteImport } from './routes/$org'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgIndexRouteImport } from './routes/$org/index'
import { Route as OrgToolsRouteImport } from './routes/$org/tools'
import { Route as OrgSecretsRouteImport } from './routes/$org/secrets'
import { Route as OrgPoliciesRouteImport } from './routes/$org/policies'
import { Route as OrgConnectionsRouteImport } from './routes/$org/connections'
import { Route as OrgSourcesNamespaceRouteImport } from './routes/$org/sources.$namespace'
import { Route as OrgChar91Char93SettingsRouteImport } from './routes/$org/[-].settings'
import { Route as OrgChar91Char93BillingRouteImport } from './routes/$org/[-].billing'
import { Route as OrgSourcesAddPluginKeyRouteImport } from './routes/$org/sources.add.$pluginKey'
import { Route as OrgChar91Char93BillingPlansRouteImport } from './routes/$org/[-].billing_.plans'

const OrgRoute = OrgRouteImport.update({
  id: '/$org',
  path: '/$org',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIndexRoute = OrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgRoute,
} as any)
const OrgToolsRoute = OrgToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => OrgRoute,
} as any)
const OrgSecretsRoute = OrgSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => OrgRoute,
} as any)
const OrgPoliciesRoute = OrgPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => OrgRoute,
} as any)
const OrgConnectionsRoute = OrgConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => OrgRoute,
} as any)
const OrgSourcesNamespaceRoute = OrgSourcesNamespaceRouteImport.update({
  id: '/sources/$namespace',
  path: '/sources/$namespace',
  getParentRoute: () => OrgRoute,
} as any)
const OrgChar91Char93SettingsRoute = OrgChar91Char93SettingsRouteImport.update({
  id: '/-/settings',
  path: '/-/settings',
  getParentRoute: () => OrgRoute,
} as any)
const OrgChar91Char93BillingRoute = OrgChar91Char93BillingRouteImport.update({
  id: '/-/billing',
  path: '/-/billing',
  getParentRoute: () => OrgRoute,
} as any)
const OrgSourcesAddPluginKeyRoute = OrgSourcesAddPluginKeyRouteImport.update({
  id: '/sources/add/$pluginKey',
  path: '/sources/add/$pluginKey',
  getParentRoute: () => OrgRoute,
} as any)
const OrgChar91Char93BillingPlansRoute =
  OrgChar91Char93BillingPlansRouteImport.update({
    id: '/-/billing_/plans',
    path: '/-/billing/plans',
    getParentRoute: () => OrgRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$org': typeof OrgRouteWithChildren
  '/$org/connections': typeof OrgConnectionsRoute
  '/$org/policies': typeof OrgPoliciesRoute
  '/$org/secrets': typeof OrgSecretsRoute
  '/$org/tools': typeof OrgToolsRoute
  '/$org/': typeof OrgIndexRoute
  '/$org/-/billing': typeof OrgChar91Char93BillingRoute
  '/$org/-/settings': typeof OrgChar91Char93SettingsRoute
  '/$org/sources/$namespace': typeof OrgSourcesNamespaceRoute
  '/$org/-/billing/plans': typeof OrgChar91Char93BillingPlansRoute
  '/$org/sources/add/$pluginKey': typeof OrgSourcesAddPluginKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$org/connections': typeof OrgConnectionsRoute
  '/$org/policies': typeof OrgPoliciesRoute
  '/$org/secrets': typeof OrgSecretsRoute
  '/$org/tools': typeof OrgToolsRoute
  '/$org': typeof OrgIndexRoute
  '/$org/-/billing': typeof OrgChar91Char93BillingRoute
  '/$org/-/settings': typeof OrgChar91Char93SettingsRoute
  '/$org/sources/$namespace': typeof OrgSourcesNamespaceRoute
  '/$org/-/billing/plans': typeof OrgChar91Char93BillingPlansRoute
  '/$org/sources/add/$pluginKey': typeof OrgSourcesAddPluginKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$org': typeof OrgRouteWithChildren
  '/$org/connections': typeof OrgConnectionsRoute
  '/$org/policies': typeof OrgPoliciesRoute
  '/$org/secrets': typeof OrgSecretsRoute
  '/$org/tools': typeof OrgToolsRoute
  '/$org/': typeof OrgIndexRoute
  '/$org/-/billing': typeof OrgChar91Char93BillingRoute
  '/$org/-/settings': typeof OrgChar91Char93SettingsRoute
  '/$org/sources/$namespace': typeof OrgSourcesNamespaceRoute
  '/$org/-/billing_/plans': typeof OrgChar91Char93BillingPlansRoute
  '/$org/sources/add/$pluginKey': typeof OrgSourcesAddPluginKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$org'
    | '/$org/connections'
    | '/$org/policies'
    | '/$org/secrets'
    | '/$org/tools'
    | '/$org/'
    | '/$org/-/billing'
    | '/$org/-/settings'
    | '/$org/sources/$namespace'
    | '/$org/-/billing/plans'
    | '/$org/sources/add/$pluginKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$org/connections'
    | '/$org/policies'
    | '/$org/secrets'
    | '/$org/tools'
    | '/$org'
    | '/$org/-/billing'
    | '/$org/-/settings'
    | '/$org/sources/$namespace'
    | '/$org/-/billing/plans'
    | '/$org/sources/add/$pluginKey'
  id:
    | '__root__'
    | '/'
    | '/$org'
    | '/$org/connections'
    | '/$org/policies'
    | '/$org/secrets'
    | '/$org/tools'
    | '/$org/'
    | '/$org/-/billing'
    | '/$org/-/settings'
    | '/$org/sources/$namespace'
    | '/$org/-/billing_/plans'
    | '/$org/sources/add/$pluginKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgRoute: typeof OrgRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$org': {
      id: '/$org'
      path: '/$org'
      fullPath: '/$org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$org/': {
      id: '/$org/'
      path: '/'
      fullPath: '/$org/'
      preLoaderRoute: typeof OrgIndexRouteImport
      parentRoute: typeof OrgRoute
    }
    '/$org/tools': {
      id: '/$org/tools'
      path: '/tools'
      fullPath: '/$org/tools'
      preLoaderRoute: typeof OrgToolsRouteImport
      parentRoute: typeof OrgRoute
    }
    '/$org/secrets': {
      id: '/$org/secrets'
      path: '/secrets'
      fullPath: '/$org/secrets'
      preLoaderRoute: typeof OrgSecretsRouteImport
      parentRoute: typeof OrgRoute
    }
    '/$org/policies': {
      id: '/$org/policies'
      path: '/policies'
      fullPath: '/$org/policies'
      preLoaderRoute: typeof OrgPoliciesRouteImport
      parentRoute: typeof OrgRoute
    }
    '/$org/connections': {
      id: '/$org/connections'
      path: '/connections'
      fullPath: '/$org/connections'
      preLoaderRoute: typeof OrgConnectionsRouteImport
      parentRoute: typeof OrgRoute
    }
    '/$org/sources/$namespace': {
      id: '/$org/sources/$namespace'
      path: '/sources/$namespace'
      fullPath: '/$org/sources/$namespace'
      preLoaderRoute: typeof OrgSourcesNamespaceRouteImport
      parentRoute: typeof OrgRoute
    }
    '/$org/-/settings': {
      id: '/$org/-/settings'
      path: '/-/settings'
      fullPath: '/$org/-/settings'
      preLoaderRoute: typeof OrgChar91Char93SettingsRouteImport
      parentRoute: typeof OrgRoute
    }
    '/$org/-/billing': {
      id: '/$org/-/billing'
      path: '/-/billing'
      fullPath: '/$org/-/billing'
      preLoaderRoute: typeof OrgChar91Char93BillingRouteImport
      parentRoute: typeof OrgRoute
    }
    '/$org/sources/add/$pluginKey': {
      id: '/$org/sources/add/$pluginKey'
      path: '/sources/add/$pluginKey'
      fullPath: '/$org/sources/add/$pluginKey'
      preLoaderRoute: typeof OrgSourcesAddPluginKeyRouteImport
      parentRoute: typeof OrgRoute
    }
    '/$org/-/billing_/plans': {
      id: '/$org/-/billing_/plans'
      path: '/-/billing/plans'
      fullPath: '/$org/-/billing/plans'
      preLoaderRoute: typeof OrgChar91Char93BillingPlansRouteImport
      parentRoute: typeof OrgRoute
    }
  }
}

interface OrgRouteChildren {
  OrgConnectionsRoute: typeof OrgConnectionsRoute
  OrgPoliciesRoute: typeof OrgPoliciesRoute
  OrgSecretsRoute: typeof OrgSecretsRoute
  OrgToolsRoute: typeof OrgToolsRoute
  OrgIndexRoute: typeof OrgIndexRoute
  OrgChar91Char93BillingRoute: typeof OrgChar91Char93BillingRoute
  OrgChar91Char93SettingsRoute: typeof OrgChar91Char93SettingsRoute
  OrgSourcesNamespaceRoute: typeof OrgSourcesNamespaceRoute
  OrgChar91Char93BillingPlansRoute: typeof OrgChar91Char93BillingPlansRoute
  OrgSourcesAddPluginKeyRoute: typeof OrgSourcesAddPluginKeyRoute
}

const OrgRouteChildren: OrgRouteChildren = {
  OrgConnectionsRoute: OrgConnectionsRoute,
  OrgPoliciesRoute: OrgPoliciesRoute,
  OrgSecretsRoute: OrgSecretsRoute,
  OrgToolsRoute: OrgToolsRoute,
  OrgIndexRoute: OrgIndexRoute,
  OrgChar91Char93BillingRoute: OrgChar91Char93BillingRoute,
  OrgChar91Char93SettingsRoute: OrgChar91Char93SettingsRoute,
  OrgSourcesNamespaceRoute: OrgSourcesNamespaceRoute,
  OrgChar91Char93BillingPlansRoute: OrgChar91Char93BillingPlansRoute,
  OrgSourcesAddPluginKeyRoute: OrgSourcesAddPluginKeyRoute,
}

const OrgRouteWithChildren = OrgRoute._addFileChildren(OrgRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgRoute: OrgRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
